### ISSUE TITLE
[BUG] Ollama embedder expecting wrong (?) key in embedder config

### ISSUE THREAD

**Issue by jaimesalazarlahera** [crewAIInc/crewAI#1994]
### Description

I was getting connection refused errors when adding an ollama embedder. I finally realized the [ollama embedding configurator](https://github.com/crewAIInc/crewAI/blob/c3e7a3ec1936fda43428ff13a3fd101f483db6af/src/crewai/utilities/embedding_configurator.py#L91) was asking the config for a `"url"` key when I was trying with `"api_url"` , `"base_url"` , `"api_base"` , etc. I couldn't find much in the docs about this.

![Image](https://github.com/user-attachments/assets/dd0dc96c-3204-42fc-8edb-651c4edf0e92)

Note: I need the url to be `ollama:11434` instead of `localhost:11434` because ollama is the docker container.

### Steps to Reproduce

1. Add a knowledge source to an agent.
2. Add the embedder to an agent. Try any of the documented examples of the ollama embedder config. For example:

```
{
    "provider": "ollama",
    "config": {
        "model": "mxbai-embed-large",
        "api_url":  "http://ollama:11434"
    }
}
```

3. Run `crewai run` and notice it will only take your config value if the key is `url`.

### Expected behavior

For it to be documented better?

### Screenshots/Code snippets

This was causing my `_session.post() `to error out:

![Image](https://github.com/user-attachments/assets/dec30f12-8adf-42ba-9e9c-8231ab58f929)

### Operating System

Other (specify in additional context)

### Python Version

3.12

### crewAI Version

0.98.0

### crewAI Tools Version

0.32.0

### Virtual Environment

Venv

### Evidence

In the main post.

### Possible Solution

More documentation, or making the url key mandatory, raising an exception if missing.

### Additional context

None

**Comment by callmeBalloch** [comment]
I think is the same: https://github.com/crewAIInc/crewAI/pull/1972

waiting for the release...

**Comment by callmeBalloch** [comment]
I fixed mine :)

```python
    embedder={
        "provider": "ollama",
        "config": {
            "model": "mxbai-embed-large",
            "url": "http://localhost:11434/api/embeddings"
        },
    }

```

**Comment by jaimesalazarlahera** [comment]
> I fixed mine :)
> 
>     embedder={
>         "provider": "ollama",
>         "config": {
>             "model": "mxbai-embed-large",
>             "url": "http://localhost:11434/api/embeddings"
>         },
>     }

Yep, I had to figure out the key must be `url` (is it documented anywhere?) and also that you have to put the full url to the `/api/embeddings` endpoint, not just the api base.

Not sure this is related to [#1972](https://github.com/crewAIInc/crewAI/pull/1972) but I'll wait for that PR to see if it works.

**Comment by jaimesalazarlahera** [comment]
Updated to 0.100.1 and still the same issue. Either I'm doing something wrong or the docs need to specify that the ollama embedder config needs to have a `url` key point at the full `/api/embeddings` endpoint.

**Comment by bhancockio** [comment]
@jaimesalazarlahera What you did here is correct

embedder={
    "provider": "ollama",
    "config": {
        "model": "mxbai-embed-large",
        "url": "http://localhost:11434/api/embeddings"
    },

We are going to be updating the docs to show this going forward
